### ISSUE TITLE
Fetch not found on server-side

### ISSUE THREAD

**Issue by kaluabentes** [dleitee/fetches#8]
For any reason fetch it's not been found on server side, it's normal? Or the lib should address SSR to?

**Comment by dleitee** [comment]
for now, to you use `fetches` into server side, you need to install any library like `node-fetch` and then, in your server define `fetch` like this:

```
import fetch from 'node-fetch'

global.fetch = fetch
```

We need to implement the server side into the library yet, feel free to contribute.
